### PR TITLE
fix: added support for decorate with the SVG multi-series

### LINKED ISSUE #11: decorate property missing from multi series
https://github.com/d3fc/d3fc-series/blob/master/src/multiBase.js

### PR DESCRIPTION
**Pull request by ColinEberhardt**
fixes #11 

should allow completion of https://github.com/d3fc/d3fc-technical-indicator/pull/37

NOTE: I have not added support for canvas multi decoration. This is because with canvas series the decorate function is inserted before the series performs its rendering logic. The multi series doesn't have an insertion point that makes sense.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
@alisd23 - this might be useful for you ...

**Comment by chrisprice** [comment]
Probably me being dumb but I don't understand why canvas can't have a decorate? Invoking decorate before [invoking the series](https://github.com/d3fc/d3fc-series/blob/master/src/canvas/multi.js#L20) seems like it would do the job...

**Comment by ColinEberhardt** [comment]
I guess the question is, could you usefully do anything at that point?

With a regular series, this is what happens within our canvas rendering logic

 1. Apply translation to the context to set the origin
 2. Set up the styles, e.g. fill and stroke colors
 3. Decorate
 4. Render

As a result the decorate function can render additional visuals at the correct origin. It can also change the context properties such as fill and stroke.

What could you usefully do by decorating before the line of code you linked to? Surely anything changes you apply to the context at that point could equally well be performed before invoking th multi-series component?

**Comment by chrisprice** [comment]
So the bit I'd missed is that decorate is run between the context setup (translation/styles) and the actual render. I now agree there isn't a simple insertion point.

It is a shame not to be able to do this though e.g. it prevents easily styling a set of lines. I wonder if we could do something more advanced by injecting decorate functions into the child series?

**Comment by alisd23** [comment]
I think the screenshot issue actually depends on this, as phantom has no default styles for svg elements, so the SVG's are invisible when the screenshot is taken. I think...

**Comment by chrisprice** [comment]
Merging to unblock @alisd23, @ColinEberhardt is going to look at adding support for canvas as well

**Pull request merged**
